### ISSUE TITLE
Detailed job description panel

### ISSUE THREAD

**Issue by DanGrew** [DanGrew/JenkinsTestTracker#43]
Provide a detailed version with culprits and test results.

**Comment by DanGrew** [comment]
Added culprits - needs configuration in build wall config panel

**Comment by DanGrew** [comment]
at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at buildwall.panel.description.FailureDetail.updateCulpritText(FailureDetail.java:148)
	at buildwall.panel.description.FailureDetail.lambda$3(FailureDetail.java:110)
	at buildwall.panel.description.FailureDetail$$Lambda$572/327839098.accept(Unknown Source)
	at utility.observable.FunctionListChangeListenerImpl$$Lambda$537/1054625189.accept(Unknown Source)

Not on JavaFx thread - fix
